services:
  my-discovery-service:
    build: ./discovery-service
    container_name: my-discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
  my-config-service:
    build: ./config-servicee
    container_name: my-config-service
    ports:
      - "9999:9999"
    expose:
      - "9999"
    environment:
      - DISCOVERY_SERVICE_URL=http://my-discovery-service:8761/eureka
      - DOCKER_HOST_NAME=my-config-service
    depends_on:
      my-discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
  my-gateway-service:
    build: ./gateway-service
    container_name: my-gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://my-discovery-service:8761/eureka
      - DOCKER_HOST_NAME=my-gateway-service
    depends_on:
      my-discovery-service:
        condition: service_healthy
  my-customer-service:
    build: ./customer-service
    container_name: my-customer-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - DISCOVERY_SERVICE_URL=http://my-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://my-config-service:9999
      - DOCKER_HOST_NAME=my-customer-service
    depends_on:
      my-config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
  my-inventory-service:
    build: ./inventory-service
    container_name: my-inventory-service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - DISCOVERY_SERVICE_URL=http://my-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://my-config-service:9999
      - DOCKER_HOST_NAME=my-inventory-service
    depends_on:
      my-config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
  my-billing-service:
    build: ./billing-service
    container_name: my-billing-service
    ports:
      - "8083:8083"
    expose:
      - "8083"
    environment:
      - DISCOVERY_SERVICE_URL=http://my-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://my-config-service:9999
      - DOCKER_HOST_NAME=my-billing-service
    depends_on:
      my-customer-service:
        condition: service_healthy
      my-inventory-service:
        condition: service_healthy



