apiVersion: v1
kind: Service
metadata:
  name: billing-svc
  labels:
    name: billing-pod
    app: billing-service
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30002
  selector:
    name: billing-pod
    app: billing-service
