apiVersion: v1
kind: Service
metadata:
  name: config-svc
  labels:
    name: config-pod
    app: config-service
spec:
  type: NodePort
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30006
  selector:
    name: config-pod
    app: config-service
