apiVersion: v1
kind: Service
metadata:
  name: customer-svc
  labels:
    name: customer-pod
    app: customer-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
  selector:
    name: customer-pod
    app: customer-service
