apiVersion: v1
kind: Service
metadata:
  name: discovery-svc
  labels:
    name: discovery-pod
    app: discovery-service
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30003
  selector:
    name: discovery-pod
    app: discovery-service
