apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    name: inventory-deployment
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      name: inventory-pod
      app: inventory-service
  template:
    metadata:
      name: inventory-pod
      labels:
        name: inventory-pod
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: hamza395/inventory-service:v1.12
          ports:
            - containerPort: 8082