name: integration-pipeline

on:
  push:
    branches:
      - main
jobs:
  building_services:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: jdk

      - name: pulling the app
        uses: actions/checkout@v6.0.1

      - name: build-discovery-service
        run: |
          cd discovery-service
          mvn clean package -DskipTests
