name: integration-pipeline

on:
  push:
    branches:
      - main
jobs:
  building_services:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: "temurin"

      - name: pulling the app
        uses: actions/checkout@v6.0.1

      - name: build-discovery-service
        run: cd discovery-service && mvn clean package -DskipTests

      - name: build-config-service
        run: cd config-servicee && mvn clean package -DskipTests

      - name: build-gateway-service
        run: cd gateway-service && mvn clean package -DskipTests

      - name: build-customer-service
        run: cd customer-service && mvn clean package -DskipTests

      - name: build-inventory-service
        run: cd inventory-service && mvn clean package -DskipTests

      - name: build-billing-service
        run: cd billing-service && mvn clean package -DskipTests

      - name: Upload Builds Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: 'builds artifacts'
          path: |
            ./discovery-service/target
            ./config-servicee/target
            ./gateway-service/target
            ./customer-service/target
            ./inventory-service/target
            ./billing-service/target

  building_images_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    environment: ci-pipeline-env
    needs:
      - building_services
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: "temurin"

      - name: pulling the app
        uses: actions/checkout@v6.0.1

      - name: cleaning services
        run: |
          cd discovery-service && mvn clean
          cd ../config-servicee && mvn clean
          cd ../gateway-service && mvn clean
          cd ../customer-service && mvn clean
          cd ../inventory-service && mvn clean
          cd ../billing-service && mvn clean

      - name: Download a Build Artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: 'builds artifacts'
          merge-multiple: true

      - name: Building docker images
        run: |
          docker build -t hamza395/discovery-service:v1.${{github.run_number}} ./discovery-service
          docker build -t hamza395/config-service:v1.${{github.run_number}} ./config-servicee
          docker build -t hamza395/gateway-service:v1.${{github.run_number}} ./gateway-service
          docker build -t hamza395/customer-service:v1.${{github.run_number}} ./customer-service
          docker build -t hamza395/inventory-service:v1.${{github.run_number}} ./inventory-service
          docker build -t hamza395/billing-service:v1.${{github.run_number}} ./billing-service

      - name: Login docker
        run: |
          echo ${{secrets.DOCKER_USERNAME}} ${{secrets.DOCKER_PASSWORD}}
          docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}

      - name: Pushing images to docker hub
        run: |
          docker image push hamza395/discovery-service:v1.${{github.run_number}}
          docker image push hamza395/config-service:v1.${{github.run_number}}
          docker image push hamza395/gateway-service:v1.${{github.run_number}}
          docker image push hamza395/customer-service:v1.${{github.run_number}}
          docker image push hamza395/inventory-service:v1.${{github.run_number}}
          docker image push hamza395/billing-service:v1.${{github.run_number}}