name: integration-pipeline

on:
  push:
    branches:
      - main
jobs:
  building_services:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: "temurin"

      - name: pulling the app
        uses: actions/checkout@v6.0.1

      - name: build-discovery-service
        run: cd discovery-service && mvn clean package -DskipTests

      - name: build-config-service
        run: cd config-servicee && mvn clean package -DskipTests

      - name: build-gateway-service
        run: cd gateway-service && mvn clean package -DskipTests

      - name: build-customer-service
        run: cd customer-service && mvn clean package -DskipTests

      - name: build-inventory-service
        run: cd inventory-service && mvn clean package -DskipTests

      - name: build-billing-service
        run: cd billing-service && mvn clean package -DskipTests

      - name: Upload Builds Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: 'builds artifacts'
          path: |
            ./discovery-service/target
            ./config-servicee/target
            ./gateway-service/target
            ./customer-service/target
            ./inventory-service/target
            ./billing-service/target

  building_images_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    needs:
      - building_services
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: "temurin"

      - name: pulling the app
        uses: actions/checkout@v6.0.1

      - name: cleaning services
        run: |
          cd discovery-service && mvn clean && ls
          cd ../config-servicee && mvn clean && ls
          cd ../gateway-service && mvn clean && ls
          cd ../customer-service && mvn clean && ls
          cd ../inventory-service && mvn clean && ls
          cd ../billing-service && mvn clean && ls

      - name: Download a Build Artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: 'builds artifacts'
          merge-multiple: true

      - name: artifacts existance verification
        run: |
          cd discovery-service && ls
          cd ../config-servicee && ls
          cd ../gateway-service && ls
          cd ../customer-service && ls
          cd ../inventory-service && ls
          cd ../billing-service && ls