name: integration-pipeline

on:
  push:
    branches:
      - main
jobs:
  building_services:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: "temurin"
      - name: Check Java version
        run: java -version

      - name: pulling the app
        uses: actions/checkout@v6.0.1

      - name: build-discovery-service
        run: cd discovery-service && mvn clean package -DskipTests

      - name: build-config-service
        run: cd config-servicee && mvn clean package -DskipTests

      - name: build-gateway-service
        run: cd gateway-service && mvn clean package -DskipTests

      - name: build-customer-service
        run: cd customer-service && mvn clean package -DskipTests

      - name: build-inventory-service
        run: cd inventory-service && mvn clean package -DskipTests

      - name: build-billing-service
        run: cd billing-service && mvn clean package -DskipTests

